package.path = "./?.lua;./?/init.lua;" .. package.path
local guard = require("guardrail")
local total = 0
local function test(name, fn) total = total + 1; local ok, err = pcall(fn); if not ok then error(name .. ": " .. tostring(err), 0) end end

test("primitive constraints and immutability", function()
  local base = guard.string(); local optional = base:optional()
  assert(not base:is_valid(nil)); assert(optional:is_valid(nil)); assert(guard.integer():is_valid(2)); assert(not guard.integer():is_valid(2.1))
end)
test("nested error path", function()
  local s = guard.table({ users = guard.array(guard.table({ email = guard.string() })) })
  local ok, err = s:validate({ users = { { email = 42 } } }); assert(not ok and err.path_string == "users[1].email")
end)
test("collects nested failures with a bound", function()
  local s = guard.table({ a = guard.string(), b = guard.integer(), c = guard.boolean() })
  local ok, errors = s:validate({ a = 1, b = "2", c = "false" }, { collect_all = true, max_errors = 2 })
  assert(not ok and #errors == 2 and errors[1].path_string == "a" and errors[2].path_string == "b")
end)
test("transforms explicitly without mutating input", function()
  local input = { name = "  Ada  ", ignored = true }
  local s = guard.table({ name = guard.string() }, { strip_unknown = true }):transform(function(v) v.name = v.name:match("^%s*(.-)%s*$"); return v end)
  local result = s:assert(input); assert(result.name == "Ada" and result.ignored == nil and input.name == "  Ada  " and input.ignored)
end)
test("transform precedes refinement while validation remains raw", function()
  local s = guard.string():transform(function(v) return v:match("^%s*(.-)%s*$") end):refine(function(v) return #v >= 3 end, "too short")
  assert(s:parse("  Ada  ") == "Ada"); assert(not s:parse(" x "))
end)
test("granular validator modules load", function()
  assert(type(require("guardrail.validators.string")) == "function")
  assert(type(require("guardrail.validators.array")) == "function")
end)
test("unknown and sparse tables", function()
  assert(not guard.table({ a = guard.string() }):is_valid({ a = "x", b = true }))
  assert(not guard.array(guard.string()):is_valid({ [2] = "x" }))
end)
test("contracts preserve nil returns", function()
  local fn = guard.contract({ args = { guard.string(), guard.optional(guard.boolean()) }, returns = guard.returns({ guard.string(), guard.optional(guard.string()) }) }, function(v) return v, nil end)
  local a, b = fn("ok"); assert(a == "ok" and b == nil)
end)
test("preconditions and disabled mode", function()
  local fn = guard.contract({ requires = function(v) return v > 0, "positive only" end, args = { guard.number() } }, function(v) return v end)
  assert(not pcall(fn, 0)); guard.with_disabled(function() assert(fn(0) == 0) end)
end)
test("invariants and cycles", function()
  local invariant = guard.invariant({ check = function(v) return v.balance >= 0 end }); local account = { balance = 1 }; assert(guard.with_invariant(invariant, account, function() return "ok" end) == "ok")
  local recursive; recursive = guard.lazy(function() return guard.table({ self = recursive }) end)
  local value = {}; value.self = value; assert(not recursive:is_valid(value))
end)
test("lazy schemas and annotations", function()
  local node; node = guard.lazy(function() return guard.table({ value = guard.string(), children = guard.array(node) }) end)
  assert(node:is_valid({ value = "root", children = { { value = "child", children = {} } } }))
  local user = guard.table({ id = guard.integer(), name = guard.optional(guard.string()) }); local text = guard.annotations.generate("User", user); assert(text:match("---@class User"))
end)
print("ok - " .. total .. " guardrail tests")
